{
 "title": "AI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flask Request Duration Seconds count",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flask_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flask_memory_usage_bytes / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Of Method Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "flask_method_calls_total", "legendFormat": "__auto" }
   ]
  }
 ]
}